twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        opening: '@App\Twig\TimesExtension'
        workshops: '@App\Twig\WorkshopsExtension'

when@test:
    twig:
        strict_variables: true
